- hosts: all
  become: yes
  become_user: root
  tasks:
          - name: Download httpd
            package:
               name: "httpd"
               state: present

          - name: copy code
            copy:
               dest: "/var/www/html/"
               src: "/root/Desktop/t2/index.html"

          - name: Start the service
            service:
               name: "httpd"
               state: started
               enabled: yes
           
               
